### ISSUE TITLE
rate and rate_per_time_unit value inf

### ISSUE THREAD

**Issue by wokkeltje13** [jomjol/AI-on-the-edge-device#1634]
### The Problem

In MQTT I noticed the value "inf" for "rate" and "rate_per_time_unit"
![image](https://user-images.githubusercontent.com/57153640/208479123-c04af4be-be18-4104-aed9-fdcebd0d844c.png)

Did I miss some release notes? 
It stopped reporting the values on 13/12, so probably after the update to 13.0.7 (but I am not sure)

Thanks in advance

### Version

13.0.7

### Logfile

```shell
[       4] 2022-12-19T16:46:32 <INF> [MAIN] =================================================
[       4] 2022-12-19T16:46:32 <INF> [MAIN] ==================== Startup ====================
[       4] 2022-12-19T16:46:32 <INF> [MAIN] =================================================
[       4] 2022-12-19T16:46:32 <INF> [MAIN] Branch: 'HEAD', Revision: 304b9e0, Date/Time: 2022-12-11 22:36, Web UI: Release: v13.0.7 (Commit: 304b9e0)
[       4] 2022-12-19T16:46:32 <INF> [MAIN] Reset reason: Via esp_restart
[       8] 2022-12-19T16:46:36 <INF> [MAIN] =================================================
[       8] 2022-12-19T16:46:36 <INF> [MAIN] ================== Main Started =================
[       8] 2022-12-19T16:46:36 <INF> [MAIN] =================================================
[      10] 2022-12-19T16:46:38 <INF> [MAIN] Initialization completed successfully!
```

**Comment by TopGoalVl** [comment]
Have a look at issue  1578. The bug is fixed in newest rolling. 
https://github.com/jomjol/AI-on-the-edge-device/issues/1578?notification_referrer_id=NT_kwDOByNa9LQ1MDgwNDc0NjM1OjExOTc1NzU1Ng#event-8039627466

**Comment by wokkeltje13** [comment]
I used the latest rolling build (I think)
"Merge for next Bugfix Release #953"
Development-Branch: HEAD (Commit: 1ee8f47+)

But after a couple of runs, the inf value remains

2022-12-19T19:18:24+0100,main,004565.0,4565.0,4565.0,inf,0.5,no error,0.0,0.0,4.0,5.0,6.0,5.0,0.2
2022-12-19T19:23:06+0100,main,004565.9,4565.9,4565.9,inf,0.9,no error,0.0,0.0,4.0,5.0,6.0,5.0,9.3
2022-12-19T19:27:56+0100,main,004565.9,4565.9,4565.9,nan,0.0,no error,0.0,0.0,4.0,5.0,6.0,5.3,9.3

Did I use the wrong build?

**Comment by TopGoalVl** [comment]
I have updated to:

Build Info:
Firmware Version: Development-Branch: rolling (Commit: 0d48c52+)
Firmware Build Time: 2022-12-18 10:20
Web Interface Version: Development-Branch: rolling (Commit: 0d48c52+)

and the bug was fixed.

**Comment by wokkeltje13** [comment]
With this exact version the bug is solved, but more recent builds still have the bug.

**Comment by caco3** [comment]
@jomol, is this working for you in rolling?

**Comment by jomjol** [comment]
@caco3 : I can confirm. The problem is back!

![grafik](https://user-images.githubusercontent.com/30766535/208508016-61063f6b-a80e-4b85-8fe2-f8f075d04527.png)

Need to fix it, before I release.

**Comment by jomjol** [comment]
Again corrected in newest rolling
