### ISSUE TITLE
Webserver unreachable

### ISSUE THREAD

**Issue by Mirko81** [jomjol/AI-on-the-edge-device#243]
The webserver is about 2-6 hours after startup no longer available.
The response is alternately ERR_EMPTY_RESPONSE or ERR_CONNECTION_RESET.
The log is without errors and ends with last action log entry.

I started the cam yesterday at 9pm. Today at 2am the last recognition was executed. At the morning i tried to connect to the webserver. After getting the errors I restarted the cam. Less than 2 hours later the webserver wasn't available again. This behaviour I observed several times before.

Do you have any idea? Thank you in advance for your support.

[log_2021-06-10.txt](https://github.com/jomjol/AI-on-the-edge-device/files/6629729/log_2021-06-10.txt)
[config.ini.txt](https://github.com/jomjol/AI-on-the-edge-device/files/6629746/config.ini.txt)

**Comment by jomjol** [comment]
The config.ini is okay. 
Regarding the log file:
* very high temperature (90°), rather 50-60°C would be expected. Do you see the LED-flash on all time?
* Looks like your ESP32 stopps and does not recover or reboot, like it is expected in case of failure. I have seen this in combination with a defect OV2640 camera. Also is seems, that there are different variant and the system stability does vary within them. 

I would test a different OV2640 to resolve this problem. It is rather not a firmware topic.

**Comment by Mirko81** [comment]
Thanks for your answer.

I don't know why, but now the webserver is continuously available. I didn't changed anything.

A temperature rather than 50-60 degrees I never get. The flash isn't always on. I noticed that every second the devices runs a DNS call.
I have an own DNS server which logs queries every second to a domain named  'd'.

Do you have any Idea?

**Comment by jomjol** [comment]
This query is strange. Could it be the mqtt adapter trying to connect?

**Comment by Mirko81** [comment]
Yes, I disabled the mqtt option and no query occured anymore.

**Comment by Mirko81** [comment]
If I disabled the mqtt option the DNS queries starting at round #2. The CPU temperature ist about 52 degrees now.

**Comment by Mirko81** [comment]
Only if I uncheck every single mqtt checkbox no more DNS query was executed. When I uncheck only the main mqtt checkbox the DNS requests nevertheless was executed.

**Comment by jomjol** [comment]
Thanks for that input, I will check the code and correct with one of the next versions.

**Comment by jomjol** [comment]
It is corrected in the acutal `rolling`.

**ATTENTION: this is going to be a major change with multi number option (e.g. dual power meters). So it is not downward compatible if you update and it is clearly in a beta stage.**

**Comment by Mirko81** [comment]
Unfortunately this error still occurs.

**Comment by jomjol** [comment]
Can you attach a logging to the serial? 

My webservers (3 running in parallel 24x7) do not have this problem. Therefore I need more information.

**Comment by Mirko81** [comment]
Attached you can find the serial log. Thank you in advance.
[serial.log](https://github.com/jomjol/AI-on-the-edge-device/files/6778131/serial.log)

**Comment by jomjol** [comment]
Thanks for the logfile. The error tells me, that there are too many parallel requests to the server. How do you access it? In one of the next versions I will open a parameter in the server, that throughs away the oldest connection. This should solve the problem, at least to some other forum discussion.
The next rolling will have this corrected.

**Comment by Mirko81** [comment]
Thanks for your analization. I connect to the server through a simple http request by using different browsers on different Windows or Android devices. I also waited some time and tried a new request later but I got the same issue.

**Comment by jomjol** [comment]
The newest rolling, just uploaded recently, has this new parameter. Please test with this one.

ATTENTION: if you have not used the rolling up to now, be careful with the upgrade. It is not downward compatible to the master version.

**Comment by Mirko81** [comment]
Thank you very much. I am on vacation some days so I will test it in a few days.

**Comment by Mirko81** [comment]
Does the latest master release include this change? I updated to the last version of master branch but the error still occures.

**Comment by jomjol** [comment]
Yes, this should include the changes. In this case, the problem seems to be somewhere else. My 4 systmems are running without  any problems.

**Comment by Mirko81** [comment]
I think I was a little bit impatient after the last update. I still get the problem that the webserver sometimes is unreachable. But when I wait some minutes and try again to reach the webserver it works perfectly. Thanks a lot for your support.
