### ISSUE TITLE
MQTT discovery configuration for HA deprecated in HA Core 2026.4

### ISSUE THREAD

**Issue by Kaibob2** [jomjol/AI-on-the-edge-device#3932]
### The Problem

Seit HA 2025.10 erscheint folgender Eintrag im Protokoll:

```
Logger: homeassistant.components.mqtt.entity
Quelle: components/mqtt/entity.py:1455
Integration: MQTT ([Dokumentation](https://www.home-assistant.io/integrations/mqtt), [Probleme](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
Erstmals aufgetreten: 09:56:58 (19 Vorkommnisse)
Zuletzt protokolliert: 09:56:59

- The configuration for entity sensor.watermeter_error uses the deprecated option `object_id` to set the default entity id. Replace the `"object_id": "watermeter_error"` option with `"default_entity_id": "sensor.watermeter_error"` in your published discovery configuration to fix this issue, or contact the maintainer of the integration that published this config to fix this. This will stop working in Home Assistant Core 2026.4
- The configuration for entity sensor.watermeter_rate_per_time_unit uses the deprecated option `object_id` to set the default entity id. Replace the `"object_id": "watermeter_rate_per_time_unit"` option with `"default_entity_id": "sensor.watermeter_rate_per_time_unit"` in your published discovery configuration to fix this issue, or contact the maintainer of the integration that published this config to fix this. This will stop working in Home Assistant Core 2026.4
- The configuration for entity sensor.watermeter_rate_per_digitization_round uses the deprecated option `object_id` to set the default entity id. Replace the `"object_id": "watermeter_rate_per_digitization_round"` option with `"default_entity_id": "sensor.watermeter_rate_per_digitization_round"` in your published discovery configuration to fix this issue, or contact the maintainer of the integration that published this config to fix this. This will stop working in Home Assistant Core 2026.4
-  The configuration for entity sensor.watermeter_timestamp uses the deprecated option `object_id` to set the default entity id. Replace the `"object_id": "watermeter_timestamp"` option with `"default_entity_id": "sensor.watermeter_timestamp"` in your published discovery configuration to fix this issue, or contact the maintainer of the integration that published this config to fix this. This will stop working in Home Assistant Core 2026.4
- The configuration for entity sensor.watermeter_json uses the deprecated option `object_id` to set the default entity id. Replace the `"object_id": "watermeter_json"` option with `"default_entity_id": "sensor.watermeter_json"` in your published discovery configuration to fix this issue, or contact the maintainer of the integration that published this config to fix this. This will stop working in Home Assistant Core 2026.4
```

### Version

16.0.0 forked to support OV3660

### Logfile

```shell
[0d00h00m00s] 2025-10-02T08:17:25	<INF>	[MAIN] =================================================
[0d00h00m00s] 2025-10-02T08:17:25	<INF>	[MAIN] ==================== Start ======================
[0d00h00m00s] 2025-10-02T08:17:25	<INF>	[MAIN] =================================================
[0d00h00m00s] 2025-10-02T08:17:25	<INF>	[SDCARD] Basic R/W check started...
[0d00h00m00s] 2025-10-02T08:17:25	<INF>	[SDCARD] Basic R/W check successful
[0d00h00m00s] 2025-10-02T08:17:25	<INF>	[MAIN] PSRAM size: 8388608 byte (8MB / 64MBit)
[0d00h00m00s] 2025-10-02T08:17:25	<INF>	[MAIN] Total heap: 4377019 byte
[0d00h00m03s] 2025-10-02T08:17:28	<INF>	[MAIN] Camera info: PID: 0x3660, VER: 0x00, MIDL: 0x00, MIDH: 0x00
[0d00h00m03s] 2025-10-02T08:17:28	<INF>	[SNTP] TimeServer: pool.ntp.org
[0d00h00m03s] 2025-10-02T08:17:28	<INF>	[SNTP] TimeZone not set, using default: CET-1CEST,M3.5.0,M10.5.0/3
[0d00h00m03s] 2025-10-02T08:17:28	<INF>	[SNTP] Configuring NTP Client...
[0d00h00m03s] 2025-10-02T10:17:28	<INF>	[SNTP] Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
[0d00h00m03s] 2025-10-02T10:17:28	<INF>	[SNTP] time zone: +0200 Delta to UTC: 7200 seconds
[0d00h00m03s] 2025-10-02T10:17:28	<INF>	[SNTP] Time is already set: 2025-10-02 10:17:28
[0d00h00m03s] 2025-10-02T10:17:28	<INF>	[MAIN] CPU frequency: 160 MHz
[0d00h00m03s] 2025-10-02T10:17:28	<INF>	[SDCARD] Folder/file presence check started...
[0d00h00m03s] 2025-10-02T10:17:28	<INF>	[SDCARD] Folder/file presence check successful
[0d00h00m03s] 2025-10-02T10:17:28	<INF>	[MAIN] Tag: 'ov3660', Release: ov3660 (Commit: bdc4bef), Date/Time: 2025-09-29 08:47, Web UI: Release: ov3660 (Commit: bdc4bef)
[0d00h00m03s] 2025-10-02T10:17:28	<INF>	[MAIN] Reset reason: Via esp_restart
[0d00h00m03s] 2025-10-02T10:17:28	<INF>	[WLANINI] SSID: xxxxxxx
[0d00h00m03s] 2025-10-02T10:17:28	<INF>	[WLANINI] Password: XXXXXXXX
[0d00h00m03s] 2025-10-02T10:17:28	<INF>	[WLANINI] Hostname: wasserzaehler
[0d00h00m03s] 2025-10-02T10:17:28	<INF>	[WLANINI] RSSIThreshold: -75
[0d00h00m03s] 2025-10-02T10:17:28	<INF>	[MAIN] WLAN config loaded, init WIFI...
[0d00h00m03s] 2025-10-02T10:17:28	<INF>	[WIFI] Automatic interface config --> Use DHCP service
[0d00h00m03s] 2025-10-02T10:17:28	<INF>	[WIFI] Set hostname to: wasserzaehler
[0d00h00m03s] 2025-10-02T10:17:28	<INF>	[WIFI] Init successful
[0d00h00m06s] 2025-10-02T10:17:31	<INF>	[WIFI] Connected to: FriBo, RSSI: -53
[0d00h00m07s] 2025-10-02T10:17:32	<INF>	[WIFI] Assigned IP: 192.168.0.162
[0d00h00m10s] 2025-10-02T10:17:35	<INF>	[SNTP] Time is synced with NTP Server pool.ntp.org: 2025-10-02 10:17:35
[0d00h00m11s] 2025-10-02T10:17:36	<INF>	[MAIN] Device info: CPU cores: 2, Chip revision: 301
[0d00h00m11s] 2025-10-02T10:17:36	<INF>	[MAIN] SD card info: Name: MSD, Capacity: 30024MB, Free: 29995MB
[0d00h00m13s] 2025-10-02T10:17:38	<INF>	[MAIN] Initialization completed successfully
[0d00h00m16s] 2025-10-02T10:17:41	<INF>	[TFLITE] Trying to load the model. If it crashes here, it ist most likely due to a corrupted model!
[0d00h00m16s] 2025-10-02T10:17:41	<INF>	[TFLITE] Trying to load the model. If it crashes here, it ist most likely due to a corrupted model!
[0d00h00m16s] 2025-10-02T10:17:41	<INF>	[LOGFILE] Set log level to WARNING
```

**Comment by z-master42** [comment]
@Seger85 I don't see any connection to AI on the edge.

This is an MQTT sensor configuration. Why is object_id even in there? I've created various MQTT sensors in YAML myself and I've never come across object_id. Can't you just delete that line? It's not supposed to be there at all.

See https://www.home-assistant.io/integrations/sensor.mqtt/

**Comment by caco3** [comment]
Thanks for pointing it out. Before I update it in our firmware:
@z-master42, you write
> Changing object_id to default_entity_id in this line will only work for HA >= 2025.10.

Do I understand it right? If I change it now, it will no longer work with HA < 2025.10? 
If yo, we only should change it in a year... 😒

**Comment by z-master42** [comment]
That's the way to do it.

Here's an example of how it's implemented in Zigbee2MQTT:
https://github.com/Koenkk/zigbee2mqtt/pull/28560

https://github.com/Koenkk/zigbee2mqtt/blob/129a80d1bb1fc8a26017650b1fb9260d093b2763/lib/extension/homeassistant.ts#L1505-L1521

**Comment by Elle4u** [comment]
Will there be a new firmware in the next months? Or how can I get rid of the "error"?
I cannot see a code change so far.?

**Comment by caco3** [comment]
Finally there is a new pre-release: https://github.com/jomjol/AI-on-the-edge-device/releases/tag/v16.1.0-RC1
Please test it and let us know within the next few weeks, so we can create the next release.

**Comment by Anto79-ops** [comment]
Hello, I've never updated before. Which file to upload? The whole zip file or the bin file?

Thanks

**Comment by caco3** [comment]
> Hello, I've never updated before. Which file to upload? The whole zip file or the bin file?

Use the `*update*` file from https://github.com/jomjol/AI-on-the-edge-device/releases/tag/v16.1.0-RC1 and upload it through the web inter face (menu `System > OTA Update`)

**Comment by Anto79-ops** [comment]
@caco3 thank you I will try this right now! Just to confirm I won't lose any of my settings? It took me awhile to get this perfect so it's running perfect right now

**Comment by SybexX** [comment]
@Anto79-ops From version 16.0.0 to 16.1.0 it shouldn't need to make any further change.
From version 15.7.0 (or earlier version) to 16.0.0 or 16.1.0 you would need to recalibrate the camera settings and some others.

To be on the safe side, you can save your settings to your PC

<img width="1021" height="444" alt="Image" src="https://github.com/user-attachments/assets/b66f9153-e40d-4fc3-a213-fb02c1937619" />

<img width="1023" height="544" alt="Image" src="https://github.com/user-attachments/assets/af59c5c8-0a31-47f4-be04-b5902480a035" />

**Comment by caco3** [comment]
@SybexX Why don't you use the Backup function (see the menu)?
It is easier to use and backups up also the images and models

**Comment by Anto79-ops** [comment]
Thanks I was thinking about doing a backup 😅 i have 0.16.0 on it now.

But I ran into another issue, while uploading the file, it failed to upload at around 60% and now the UI of the device is not working, but the device is working via mqtt and updating.

At the moment I'm out of town and have no way of power cycling the device so ill have to wait until I get home or the device sorts itself out. 

Is there a way to send a reboot signal via Home Assistant actions?

**Comment by caco3** [comment]
There is no way yet to restart through MQTT.
You can use `http://<IP>/reboot` if it still responds to this.

**Comment by SybexX** [comment]
@caco3 When updating, only the config.ini is usually overwritten and the rest is not touched, so config.ini is always enough for me.

**Comment by caco3** [comment]
> [@caco3](https://github.com/caco3) When updating, only the config.ini is usually overwritten and the rest is not touched, so config.ini is always enough for me.

This is only partially correct!
The update file does not contain the `config.ini` file.
But the firmware does some migration when it detects old parameters. How ever like you said, this is only happening for parameters from older installations. I thus would not call it "overwritten" but instead "updated".

**Comment by Elle4u** [comment]
EDIT: Forget it - I had to delete all old entries out of the MQTT-Explorer - seems to be good, now.


-------------------------
Thanks for the update. But I have to report, that the problem is not solved in this RC:

`2025-12-30 13:37:50.832 WARNING (MainThread) [homeassistant.components.mqtt.entity] The configuration for entity sensor.wasseruhr_rate_per_digitalization_round uses the deprecated option `object_id` to set the default entity id. Replace the `"object_id": "Wasseruhr_rate_per_digitalization_round"` option with `"default_entity_id": "sensor.Wasseruhr_rate_per_digitalization_round"` in your published discovery configuration to fix this issue, or contact the maintainer of the integration that published this config to fix this. This will stop working in Home Assistant Core 2026.4`

**Comment by z-master42** [comment]
> Finally there is a new pre-release: https://github.com/jomjol/AI-on-the-edge-device/releases/tag/v16.1.0-RC1 Please test it and let us know within the next few weeks, so we can create the next release.

Works for me. Thank you. The warnings are gone. It's also nice that the uptime now has a state class and can display more than just seconds.

**Comment by Anto79-ops** [comment]
thanks all, I'll have to provide feedback on RC1 on late Jan 1st. The UI of the device and any access via the IP is not working after the failed upload update. MQTT is still working howveer, and the device is reading numbers I will have to powercycle it when I home. Post later.

**Comment by Anto79-ops** [comment]
hello all, looks like i managed so corrupt soemthing here.

It got stuck many times trying to upload and at one point it it was 78% done and claimed it was finished and validating the file, which is was stuck on. So after many reboots im now at this screen when I go to the IP address

<img width="935" height="251" alt="Image" src="https://github.com/user-attachments/assets/bdb04c12-f4a0-4f79-9251-92a8f75b1088" />

If i click on any of the buttons the link does not work. Can I fix this without taking the SD card?

I did make a backup before all this, so if all else fails.

**Comment by SybexX** [comment]
https://jomjol.github.io/AI-on-the-edge-device-docs/Error-Codes/#0x00000010-sd-folder-or-file-presence-check-failed

Have you tried accessing the pages directly?

http://your_ip/fileserver/
http://your_ip/log.html
http://your_ip/info.html
http://your_ip/data.html
http://your_ip/backup.html
http://your_ip/ota_page.html
.........

**Comment by Anto79-ops** [comment]
Only fileserver works, but it seems none of the other work.

Would I be able to manually upload the update.zip file into the firwmware directory and reboot?

EDIT: looking at my file structure, looks like many things are missing

<img width="952" height="427" alt="Image" src="https://github.com/user-attachments/assets/50d3f062-2ea6-4c87-a1da-eb758784b0b8" />

**Comment by SybexX** [comment]
if http://your_ip/ota_page.html doesn't work, you can only try to upload the missing files manually.

It looks like the entire html folder is missing, all the others are there.

**Comment by Anto79-ops** [comment]
thanks @SybexX im trying to start from scratch (and the upload my backup files), however, simply moving the the sdcard from the unzipped file [AI-on-the-edge-device__manual-setup__v16.1.0-RC1_.71766e1.zip](https://github.com/jomjol/AI-on-the-edge-device/releases/download/v16.1.0-RC1/AI-on-the-edge-device__manual-setup__v16.1.0-RC1_.71766e1.zip), results in a strange and unresponsive UI, like this:

<img width="1113" height="909" alt="Image" src="https://github.com/user-attachments/assets/7ced4ce2-3ed9-4603-8c17-4463b398e380" />

however, I suspect I need to re-flash the esp32 device, which is something I have not done yet for 0.16.1.0-RC1. Is this something I have to do?

**Comment by SybexX** [comment]
can you access the OTA page now?

It might help if you take the html files from the version that was previously installed.

**Comment by SybexX** [comment]
You could also take a look at what the console shows:

<img width="1022" height="819" alt="Image" src="https://github.com/user-attachments/assets/89755a71-706e-4728-b78e-6409379270b4" />

**Comment by Anto79-ops** [comment]
@SybexX thank you. I uploaded the html folder from 0.16.0 and rebooted, it was a acting as if It was a fresh install asking me to run the setup wizard. I then trasnfered my backup config files to the new system config files and after some time it started working again as 0.16.0. I then ran the OTA process again, and this time it worked. It completed the upload, and installed it, and when it came back, it was 0.16.1-RC1.

<img width="1027" height="897" alt="Image" src="https://github.com/user-attachments/assets/34729aaf-a1e1-4bcc-b5fd-ee728116e198" />

Ok, I must admit, the process was pretty painful to update and I don't know why it was. The browser console logs said "timeout connecting to device"  so this might be the issue. Maybe the browser cache? but why did the device upload and then stop and not continue? On the scuesseful attempt, the the upload and update process would pause when the device is doing its digitization, but then continue the upload/update when it was done digitization. Perhaps a fresh install of the device did help here (some how).

Ok, as for RC1 test, I will keep an eye on the logs to see if teh mqtt error comes (back).

Cheers!

**Comment by Anto79-ops** [comment]
I can confirm that  0.16.1.0-RC1 fixes the MQTT discovery configuration deprecation notice. I don't see this log anymore. thank you!

**Comment by Anto79-ops** [comment]
EDIT: Update, after reformating and start over, and placing the camera a close as possible to the position it was when I trained the model, now everything is working perfectly again on RC1. Ok. all is back to being excellent. Not sure why I had to do this, probably the camera not pefectly put back in the position it was before. But wanted to reaffirm that  no issues on RC1 (probaby just user error :) thanks for the support!)

**Comment by bitzer-git** [comment]
I updated both of my systems to 16.1.0 but still see the issue for "rate_per_digitalization_round":

`2026-01-18 09:19:18.938 WARNING (MainThread) [homeassistant.components.mqtt.entity] The configuration for entity sensor.wasserkalt_rate_per_digitalization_round uses the deprecated option "object_id" to set the default entity id. Replace the "object_id": "wasserkalt_rate_per_digitalization_round" option with "default_entity_id": "sensor.wasserkalt_rate_per_digitalization_round" in your published discovery configuration to fix this issue, or contact the maintainer of the integration that published this config to fix this. This will stop working in Home Assistant Core 2026.4`

For all other entities the problem is fixed. Would it make sense to reopen the ticket or should I create a new one?

**Comment by Sourcer63** [comment]
> I updated both of my systems to 16.1.0 but still see the issue for "rate_per_digitalization_round":

Same here. Warning messages continue to be generated for both my gas and water meters.

**Comment by caco3** [comment]
I have to confess that I (due to lack of time and priorities) did not fully test it myself. I checked the PR (https://github.com/jomjol/AI-on-the-edge-device/pull/3970/files) and found it feasable. Also the feedback was positive.

So it is not applied to all topics, we should look into extending it. I am currently not active writing code in this project, but I will take the time to review new PRs.

**Comment by Anto79-ops** [comment]
Sometimes old retained messages can cause false positives. Maybe try purging the mqtt device with MQTT Explorer and resend discovery.

**Comment by Sourcer63** [comment]
@Anto79-ops , both the device and HA were restarted a dozen times. Hence any wrong message should have been corrected, I also triggered a manual discovery process several times, generating the same message in each case.

Have you meanwhile upgraded to the official release or are you still on 16.1.0-RC1?

16.1.0 is sending this object id definition:
`[0d00h00m58s] 2026-01-18T17:42:03 <DBG> [MQTT IF] Published topic: homeassistant/sensor/watermeter/raw/config, content: {"~": "watermeter","unique_id": "watermeter-raw","object_id": "watermeter_raw","..`

As you can see, it lacks the leading 'sensor.'

**Comment by Anto79-ops** [comment]
ah, good point @Sourcer63 I am still on RC1. Its a bit of a pain to update my device because sometimes I have to move the device and do it manually via SD card, which causes alignment model issues.

Anyways, long story short, its possilble the problem can still exist for some.

P.S. anyone recommed a good SD-Card extenstion cord for the ESP32-Cam? This would allow me to to testing more efficiently without have to move the device and re-train the model. I will open up a discussion on this in the correct section.

**Comment by Sourcer63** [comment]
@SybexX , would you mind taking a look?

**Comment by SybexX** [comment]
@Sourcer63 Since I don't have HA (I use IoBroker) and therefore don't know much about it, I can't really help with that.
I've looked in a few forums and this change seems to have helped in all of them, so I don't know why this message still appears(I would have to get more familiar with HA first, but I don't have the time for that).
If you want, you can try the [develop](https://github.com/jomjol/AI-on-the-edge-device/actions/runs/21117510803) firmware, I changed a few things there regarding MQTT and maybe it will help.

**Comment by Sourcer63** [comment]
Thank you for your reply. I can certainly give it a try. 

Actually it's simply about how the discovery process is naming the different entities. HA is now calling for new id definitions: 

Currently issued:  `"object_id": "gasmeter_rate_per_digitalization_round"
New convention:  "default_entity_id": "sensor.gasmeter_rate_per_digitalization_round"

So in essence _object_id_ becomes _default_entity_id_ and the names get an additional leading _sensor_ If by any chance your recent changes apply these elements, you have probably resolved the issue. 

Could you shortly describe the kind od change that you made in 16.1.0?

EDIT:  The id handling is taking place in server_mgtt.cpp here, correct?

```
 /* See https://www.home-assistant.io/docs/mqtt/discovery/ */
    payload = string("{")  +
        "\"~\": \"" + maintopic + "\","  +
        "\"unique_id\": \"" + maintopic + "-" + configTopic + "\","  +
        "\"object_id\": \"" + maintopic + "_" + configTopic + "\","  + // Default entity ID; required for HA <= 2025.10
        "\"default_entity_id\": \"" + component + "." + maintopic + "_" + configTopic + "\"," + // Default entity ID; required in HA >=2026.4
        "\"name\": \"" + name + "\","  +
        "\"icon\": \"mdi:" + icon + "\",";     
```
My C language skills are quite limited, but it looks as if object_id and default_entity_id are declared within the same string. The string gets quite long and is truncated in the log, so that I can't verify what is actually transmitted. Shouldnt it be either the one or the other, with object_id used solely for HA <=2025.10?

**Comment by SybexX** [comment]
It will both "object_id:" and "default_entity_id: sensor." sent and HA should use prioritized "default_entity_id" if it is present and ignore object_id, at least that's what I've read in countless forums.

**Comment by Sourcer63** [comment]
Obviously this is not what it does. :-)

May well be a bug in HA. I will ask a question in the HA forum and get back here.

**Comment by SybexX** [comment]
I don't know if it causes problems or not, but "rate_per_digitization_round" had nothing entered in device_class while "rate_per_time_unit" has "volume_flow_rate" as device_class.

**Comment by Sourcer63** [comment]
Hm, I don't think so,. It could be though that once the id issue gets fixed, HA then recognizes a new problem with a missing device class. Just guessing at this point.

**Comment by Sourcer63** [comment]
Question posted in HA forum:  https://community.home-assistant.io/t/mqtt-discovery-information-not-correctly-interpreted/976459

**Comment by caco3** [comment]
> I updated both of my systems to 16.1.0

FYI: There is no functional difference between v16.1.0-RC1 and v16.1.0!

Also I check my HA log and do not see any error regarding AIOTED. (The discovery functionality is in use).
The code version is 2026.1.2 which is AFIK the latest.

**Comment by Sourcer63** [comment]
The payload string is as per the code, as expected :-)

```
2026-01-18 22:26:09.621 DEBUG (MainThread) [homeassistant.components.mqtt.discovery] Component has already been discovered: sensor watermeter json, sending update
2026-01-18 22:26:09.621 DEBUG (MainThread) [homeassistant.components.mqtt.entity] Got update for entity with hash: ('sensor', 'watermeter json') '{'unique_id': 'watermeter-json', 'object_id': 'watermeter_json', 'default_entity_id': 'sensor.watermeter_json', 'icon': 'mdi:code-json', 'state_topic': 'watermeter/main/json', 'entity_category': 'diagnostic', 'availability_topic': 'watermeter/connection', 'payload_available': 'connected', 'payload_not_available': 'connection lost', 'device': {'identifiers': ['watermeter'], 'model': 'Meter Digitizer', 'manufacturer': 'AI on the Edge Device', 'sw_version': 'v16.1.0', 'configuration_url': 'http://192.168.178.116', 'name': 'watermeter'}, 'name': 'JSON'}'
2026-01-18 22:26:09.621 DEBUG (MainThread) [homeassistant.components.mqtt.entity] Ignoring unchanged update for: sensor.watermeter_json
```
It's the last line that is interesting. Do I maybe need to delete the devices in MQTT and rediscover them?

**Comment by Sourcer63** [comment]
> Do I maybe need to delete the devices in MQTT and rediscover them?

That did it! So HA doesn't completely update the MQTT devices when the payload information later changes after the initial discovery.

**Comment by bitzer-git** [comment]
How can I delete the devices in MQTT? In my setup I have HA and mosquitto running under docker.

**Comment by Sourcer63** [comment]
Open the MQTT integration page. Delete the devices that trigger the warnings and restart HA. Then launch the discovery process on the AIOTED website of the devices.

<img width="2070" height="1066" alt="Image" src="https://github.com/user-attachments/assets/5b8e5d6a-22b3-4a94-a0ef-2ce5198a7052" />

**Comment by bitzer-git** [comment]
@Sourcer63 Thanks. It works for me now as well and the warning is gone.
I recognised one change that might be the root cause of the problem. The warning was for wasserwarm_rate_per_digitalization_round. It seems like the name changed at some time to wasserwarm_rate_per_digitization_round. After deleting the device and added it again, the old name with _digitalization_ instead of _digitization_ disappeared.

**Comment by caco3** [comment]
> After deleting the device and added it again, the old name with _digitalization_ instead of _digitization_ disappeared.

Have a look on the release notes of https://github.com/jomjol/AI-on-the-edge-device/releases/tag/v16.0.0

**Comment by bitzer-git** [comment]
Ok, my conclusion would be that 16.1.0 fixes the problem with the warning already. There is no additional code change required. The remaining warning on the _digitalization_ entity can (only) be fixed by deleting and adding the device in the MQTT integration.

**Comment by caco3** [comment]
please take more care about the version. There is no 1.6.0!

And the fix got added in 16.1.0. It actually was one of the reasons for the release.

**Comment by bitzer-git** [comment]
Sorry, it was maybe already too late yesterday. My comment was only, that the main fix from 16.1.0 is working and only my problem posted yesterday with the remaining warning in HA is caused by the renaming and could easily be fixed within HA.

**Comment by BassBoi** [comment]
I will add my 5 cents here.
First of all, thank you for the fix.
The update 16.1.0 is working, it solved the problem with MQTT and HA after deleting and re-discovering.
All the recognition is as was before.
Only one thing i had to do is manual power off / power on (unplug the device from electricity) because it could not discover the camera after OTA update from v 16.0.0. (ESP32-CAM module) - might update the docu about it.. that it can happen..
here is boot log (IP's redacted:

0d00h00m00s] 2026-01-19T15:08:50 <INF> [MAIN] =================================================
[0d00h00m00s] 2026-01-19T15:08:50 <INF> [MAIN] ==================== Start ======================
[0d00h00m00s] 2026-01-19T15:08:50 <INF> [MAIN] =================================================
[0d00h00m00s] 2026-01-19T15:08:50 <INF> [SDCARD] Basic R/W check started...
[0d00h00m00s] 2026-01-19T15:08:50 <INF> [SDCARD] Basic R/W check successful
[0d00h00m00s] 2026-01-19T15:08:50 <INF> [MAIN] PSRAM size: 8388608 byte (8MB / 64MBit)
[0d00h00m00s] 2026-01-19T15:08:50 <INF> [MAIN] Total heap: 4377019 byte
[0d00h00m02s] 2026-01-19T15:08:52 <WRN> [MAIN] Camera init failed (0x105), retrying...
[0d00h00m05s] 2026-01-19T15:08:55 <ERR> [MAIN] Camera init failed (0x105)! Check camera module and/or proper electrical connection
[0d00h00m05s] 2026-01-19T15:08:55 <ERR> [HELPER] New System Status: 0x00000004
[0d00h00m05s] 2026-01-19T15:08:55 <INF> [SNTP] TimeServer not defined, using default: pool.ntp.org
[0d00h00m05s] 2026-01-19T15:08:55 <INF> [SNTP] Configuring NTP Client...
[0d00h00m05s] 2026-01-19T16:08:55 <INF> [SNTP] Time zone set to CET-1CEST,M3.5.0,M10.5.0/3
[0d00h00m05s] 2026-01-19T16:08:55 <INF> [SNTP] time zone: +0100 Delta to UTC: 3600 seconds
[0d00h00m05s] 2026-01-19T16:08:55 <INF> [SNTP] Time is already set: 2026-01-19 16:08:55
[0d00h00m05s] 2026-01-19T16:08:55 <INF> [MAIN] CPU frequency: 160 MHz
[0d00h00m05s] 2026-01-19T16:08:55 <INF> [SDCARD] Folder/file presence check started...
[0d00h00m05s] 2026-01-19T16:08:55 <INF> [SDCARD] Folder/file presence check successful
[0d00h00m05s] 2026-01-19T16:08:55 <INF> [MAIN] Tag: 'v16.1.0', Release: v16.1.0 (Commit: a1ccda2), Date/Time: 2026-01-11 22:38, Web UI: Release: v16.1.0 (Commit: a1ccda2)
[0d00h00m05s] 2026-01-19T16:08:55 <INF> [MAIN] Reset reason: Via esp_restart
[0d00h00m05s] 2026-01-19T16:08:55 <INF> [WLANINI] SSID: IoT
[0d00h00m05s] 2026-01-19T16:08:55 <INF> [WLANINI] Password: XXXXXXXX
[0d00h00m05s] 2026-01-19T16:08:55 <INF> [WLANINI] IP-Address: XXXXXXXX
[0d00h00m05s] 2026-01-19T16:08:55 <INF> [WLANINI] Gateway: XXXXXXXX1
[0d00h00m05s] 2026-01-19T16:08:55 <INF> [WLANINI] Netmask: XXXXXXXX
[0d00h00m05s] 2026-01-19T16:08:55 <INF> [WLANINI] RSSIThreshold: -75
[0d00h00m05s] 2026-01-19T16:08:55 <INF> [MAIN] WLAN config loaded, init WIFI...
[0d00h00m05s] 2026-01-19T16:08:55 <INF> [WIFI] Manual interface config -> IP: XXXXXXXX, Gateway: XXXXXXXX, Netmask: XXXXXXXX
[0d00h00m05s] 2026-01-19T16:08:55 <INF> [WIFI] No DNS server, use gateway
[0d00h00m05s] 2026-01-19T16:08:55 <INF> [WIFI] Set hostname to: watermeter
[0d00h00m05s] 2026-01-19T16:08:55 <INF> [WIFI] Init successful
[0d00h00m08s] 2026-01-19T16:08:58 <INF> [WIFI] Connected to: IoT, RSSI: -77
[0d00h00m08s] 2026-01-19T16:08:58 <INF> [WIFI] Assigned IP: XXXXXXXX
[0d00h00m09s] 2026-01-19T16:08:59 <INF> [SNTP] Time is synced with NTP Server pool.ntp.org: 2026-01-19 16:08:59
[0d00h00m09s] 2026-01-19T16:08:59 <INF> [MAIN] Device info: CPU cores: 2, Chip revision: 100
[0d00h00m09s] 2026-01-19T16:09:00 <INF> [MAIN] SD card info: Name: WX32G, Capacity: 30436MB, Free: 3635MB
[0d00h00m11s] 2026-01-19T16:09:02 <ERR> [MAIN] Initialization failed. Flow task start aborted. Loading reduced web interface...
[0d00h00m12s] 2026-01-19T16:09:02 <ERR> [MAIN SERVER] We have a critical error, not serving main page!
[0d00h00m12s] 2026-01-19T16:09:02 <ERR> [MAIN SERVER] We have a critical error, not serving main page!

Thank you for keeping the project alive 👍 💯 🥇
