### ISSUE TITLE
Unambigoius digits ('N')

### ISSUE THREAD

**Issue by ckoeber83** [jomjol/AI-on-the-edge-device#887]
Hi,

is there a possibility to always print out the last valid value (e.g. 615) instead of given a raw output of unambigoius digits (e.g. 61N)?

Here my read out log: (no error means value was proper reading)

![grafik](https://user-images.githubusercontent.com/52466072/181883530-dddfc992-837f-42b9-93b9-c48600c24e66.png)

I always try the parameter `ErrorMessage = true / false` & `CheckDigitIncreaseConsistency = true / false` & `PreValueUse = true` but without any other results.

I found the Consistency Check in [wiki ](https://github.com/jomjol/water-meter-system-complete#consistency-check)by using the parameter `usePreValue` which is might be the `PreValueUse` parameter? But this is true and does not solve the unambigoius digits ('N') output.

Here is my config:

```
[MakeImage]
LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
LogfileRetentionInDays = 15
Brightness = -2
Contrast = 2
Saturation = 2
LEDIntensity = 3
ImageQuality = 12
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 87
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = false
/config/ref0.jpg 434 47
/config/ref1.jpg 110 152

[Digits]
Model = /config/dig1400s2q.tflite
;CNNGoodThreshold = 
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
main.dig1 199 22 44 70
main.dig2 243 22 44 70
main.dig3 287 22 44 70
main.dig4 331 22 44 70
main.dig5 377 22 44 70

[Analog]
Model = /config/ana1000s2.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
main.ana1 417 192 85 85
main.ana2 353 259 85 85
main.ana3 263 280 85 85
main.ana4 160 226 85 85

[PostProcessing]
main.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 720
AllowNegativeRates = false
;main.MaxRateValue = 1.05
;main.MaxRateType = RateChange
;main.ExtendedResolution = false
;main.IgnoreLeadingNaN = true
;ErrorMessage = false
;CheckDigitIncreaseConsistency = false
```
![grafik](https://user-images.githubusercontent.com/52466072/181890640-fb7f6c22-bfb0-4669-8889-72ab47c7ed6e.png)

**Comment by JensHoRi** [comment]
As you see, the clear value gives back 615 instead of 61N, but the rate is negative (read your log) 
Example: your first value 61N.9619 (=615.9619) is lower than pre read value of 615.9699. So the negative rate causes this error, because you don’t allow negative rates in your configuration. I think your problem is more the analog counter reading.

**Comment by ckoeber83** [comment]
Hi JensHoRi,

thanks for your reply.
That's true that they ofen read a lower value than before and so it comes to a Neg. Rate effect which I don't want to allow. (My water meter does not count backwards either)

But if it would recognize the last digit correctly in the digital counter or remember it from the last successful readout, the digital counter would already be at 616, as in the example below, and there would therefore be no Neg. Rate anymore. Since he has not yet read in the last digit by the digit change, the system thinks it is still a "5" and evaluates the decimal place as a neg. rate. Rate.

![grafik](https://user-images.githubusercontent.com/52466072/182015182-9ad7b69c-36c0-41a9-be0b-612d71a60298.png)

Are there any option to nail on the last readout digit and recognize the last digit correctly?

**Comment by JensHoRi** [comment]
Until yet, the 6 never got read successfull, that’s the reason why it’s still N=5.

Jomjol is working also to read prevalues in digits, so it would be read as a 5,8 then knows it should be six. For this wait for further releases. 

Furthermore: your regions of interest looks like to big. But easier to check with a screen of regions of interest configuration. 

The inner square need to be exactly the size of the numbers

**Comment by ckoeber83** [comment]
Hi [JensHoRi](https://github.com/JensHoRi),

thanks for your reply.
Here is my screen of regions of interest configuration for review:

**ROI digital**
![grafik](https://user-images.githubusercontent.com/52466072/182245934-c7ecd9ab-5b5c-481e-bba1-07bf7223d44e.png)

**ROI analog**
![grafik](https://user-images.githubusercontent.com/52466072/182246261-83a96dc1-fed3-4199-a183-08da40a7a452.png)

Thanks for taking a look. Maye I can optimize something a bit. ;-)

Due to the recording notch for the pulse output, i never have an exact count in the analog range. However, this is not that important to me. But the digital counters should always be read correctly.

But today i had a misinterpretation of 610... & 619... although the digital counter at 617... stands.
![grafik](https://user-images.githubusercontent.com/52466072/182247174-3b0e7b39-3f42-43c2-9bdc-701647995469.png)

I correct that by setting the prevalue back to 617.2596.
But I don't always want to have to check and correct it manually.

Thank in advance.

**Comment by JensHoRi** [comment]
Your Digitals are all too big. The inner rectangle should be exact the outer of eg the 0. all digitals should be smaller. If eh the 4 is exactly in the inner rectangle, this will give better results. 

Because of the numbers behind your . :

if digits work, you could create 3 counter groups:
A with digits an 0,1 value as analog (left shift 1)
B with only 0,01 as digital value left shift 2 (the black one has value always on top)
C with only analog (if that work, don’t know) for 0.001 and 0.0001 left shift 3

if your smart home does the sum of all three you would get exact numbers.

but first concentrate on digits.

you should look in wiki, there are examples for good and bad configuration 

![](https://github.com/jomjol/AI-on-the-edge-device/wiki/images/ROI_drawing.jpg)

link to wiki: https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration

**Comment by ckoeber83** [comment]
Hi [JensHoRi](https://github.com/JensHoRi),

I updated my regions of interest for digital and analog counters to fit the frame closer to the numbers.
By this I created a new reference Image and see that the old image was decentralized. I correct that by rearrange the regions of interest digits.

Here the result:
**Digital ROI**
![image](https://user-images.githubusercontent.com/52466072/182478195-3ea260b2-3b0f-453d-9af9-ef5f06adb6e2.png)

**Analog ROI**
![image](https://user-images.githubusercontent.com/52466072/182479523-f17a85d5-9097-4a08-b980-64c8d7b8a7ef.png)


The thing with the 3 counter groups I did not understood. Maybe it's to late🙄

BR

**Comment by JensHoRi** [comment]
Does it have some positive effect on recognition?

well, the black one is not an analog counter, because it has no needle. So it needs to be configured as digital with a small square at the top number.

so you have
Dig1: 0
Dig2: 0
Dig3: 6
Dig4: 1
Dig5: 8
Analog1: 8
Dig6 (black): 6
Analog2: 9
Analog3: 8

a Reading starts with digits, then analog. 

Your mix doesn’t work with one reading.

You actual configured ‚main‘ with 5 digits and 4 analog. 

Because the black could only be read digital, you need 3 groups and AI assists more than one reading per picture.

‚Main‘:
Dig1: 0
Dig2: 0
Dig3: 6
Dig4: 1
Dig5: 8
Analog1: 8
results in 006188 (left shift 1) will be 00618.8

‚GroupB‘ (Click on new next to mail)
Dig6 (black): 6
Analog2: 9
Analog3: 8
Results in 698 (left shift 5) wil be 0.0698

if you add in your smarthome you got the exact value

**Comment by ckoeber83** [comment]
Hi [JensHoRi](https://github.com/JensHoRi),

I'd say it's worse.
In the reference image, everything is aligned appropriately.
![image](https://user-images.githubusercontent.com/52466072/182553227-4233e53f-b51c-4062-865e-02acaf41b792.png)
![image](https://user-images.githubusercontent.com/52466072/182553692-9cf79139-f8f9-48af-a81e-e6f62aeb3766.png)

But when I look into the Overview or Recognition it looks a bit out of place:
![image](https://user-images.githubusercontent.com/52466072/182553853-42c7150a-e098-4202-a532-710e6ff61c6a.png)

And based on the log it has not read the last digit proper since realignment:
```
  | 2022-08-03 09:37:52 | Neg. Rate - Read:  - Raw: 0061N.2662 - Pre: 619.9899
  | 2022-08-03 09:33:01 | Neg. Rate - Read:  - Raw: 0061N.2896 - Pre: 619.9899
  | 2022-08-03 09:28:10 | Neg. Rate - Read:  - Raw: 0061N.2892 - Pre: 619.9899
  | 2022-08-03 09:23:19 | Neg. Rate - Read:  - Raw: 0031N.2592 - Pre: 619.9899
  | 2022-08-03 09:18:28 | Neg. Rate - Read:  - Raw: 0061N.2692 - Pre: 619.9899
  | 2022-08-03 09:13:37 | Neg. Rate - Read:  - Raw: 0061N.2900 - Pre: 619.9899
  | 2022-08-03 09:08:46 | Neg. Rate - Read:  - Raw: 0061N.2700 - Pre: 619.9899
  | 2022-08-03 09:03:55 | Neg. Rate - Read:  - Raw: 0061N.2600 - Pre: 619.9899
  | 2022-08-03 08:59:04 | Neg. Rate - Read:  - Raw: 0061N.2800 - Pre: 619.9899
  | 2022-08-03 08:54:13 | Neg. Rate - Read:  - Raw: 0061N.2600 - Pre: 619.9899
  | 2022-08-03 08:49:22 | Neg. Rate - Read:  - Raw: 0061N.2800 - Pre: 619.9899
  | 2022-08-03 08:44:31 | Neg. Rate - Read:  - Raw: 0061N.2589 - Pre: 619.9899
  | 2022-08-03 08:39:40 | Neg. Rate - Read:  - Raw: 0061N.2689 - Pre: 619.9899
  | 2022-08-03 08:34:49 | Neg. Rate - Read:  - Raw: 0061N.2589 - Pre: 619.9899
  | 2022-08-03 08:29:58 | Neg. Rate - Read:  - Raw: 0061N.2689 - Pre: 619.9899
  | 2022-08-03 08:25:07 | Neg. Rate - Read:  - Raw: 0061N.2663 - Pre: 619.9899
  | 2022-08-03 08:20:16 | Neg. Rate - Read:  - Raw: 0061N.2663 - Pre: 619.9899
  | 2022-08-03 08:15:25 | Neg. Rate - Read:  - Raw: 0061N.2662 - Pre: 619.9899
  | 2022-08-03 08:10:34 | Neg. Rate - Read:  - Raw: 0061N.2662 - Pre: 619.9899
  | 2022-08-03 08:05:43 | Neg. Rate - Read:  - Raw: 0061N.2659 - Pre: 619.9899
  | 2022-08-03 08:00:52 | Neg. Rate - Read:  - Raw: 0061N.2642 - Pre: 619.9899
  | 2022-08-03 07:56:01 | Neg. Rate - Read:  - Raw: 0061N.2626 - Pre: 619.9899
  | 2022-08-03 07:51:10 | Neg. Rate - Read:  - Raw: 0061N.2819 - Pre: 619.9899
  | 2022-08-03 07:46:19 | Neg. Rate - Read:  - Raw: 0061N.1660 - Pre: 619.9899
  | 2022-08-03 07:41:28 | Neg. Rate - Read:  - Raw: 0061N.1590 - Pre: 619.9899
  | 2022-08-03 06:57:49 | Neg. Rate - Read:  - Raw: 0061N.1590 - Pre: 619.9899
  | 2022-08-03 06:52:58 | Neg. Rate - Read:  - Raw: 0061N.1690 - Pre: 619.9899
  | 2022-08-03 06:48:07 | Neg. Rate - Read:  - Raw: 0061N.1590 - Pre: 619.9899
  | 2022-08-03 06:28:43 | Neg. Rate - Read:  - Raw: 0061N.1590 - Pre: 619.9899
  | 2022-08-03 06:23:52 | Neg. Rate - Read:  - Raw: 0061N.1591 - Pre: 619.9899
  | 2022-08-03 06:19:01 | Neg. Rate - Read:  - Raw: 0061N.1590 - Pre: 619.9899
  | 2022-08-03 06:09:19 | Neg. Rate - Read:  - Raw: 0061N.1590 - Pre: 619.9899
  | 2022-08-03 06:04:28 | Neg. Rate - Read:  - Raw: 0061N.0659 - Pre: 619.9899
  | 2022-08-03 05:59:37 | Neg. Rate - Read:  - Raw: 0061N.9403 - Pre: 619.9899
  | 2022-08-03 05:54:46 | Neg. Rate - Read:  - Raw: 0061N.9620 - Pre: 619.9899
  | 2022-08-03 05:49:55 | Neg. Rate - Read:  - Raw: 0061N.9520 - Pre: 619.9899
  | 2022-08-03 05:45:04 | Neg. Rate - Read:  - Raw: 0061N.9620 - Pre: 619.9899
  | 2022-08-03 05:25:40 | Neg. Rate - Read:  - Raw: 0061N.9620 - Pre: 619.9899
  | 2022-08-03 05:20:49 | Neg. Rate - Read:  - Raw: 0061N.9520 - Pre: 619.9899
  | 2022-08-03 05:15:58 | Neg. Rate - Read:  - Raw: 0061N.9620 - Pre: 619.9899
  | 2022-08-03 05:06:16 | Neg. Rate - Read:  - Raw: 0061N.9620 - Pre: 619.9899
  | 2022-08-03 05:01:25 | Neg. Rate - Read:  - Raw: 0061N.9530 - Pre: 619.9899
  | 2022-08-03 04:56:34 | Neg. Rate - Read:  - Raw: 0061N.9620 - Pre: 619.9899
  | 2022-08-03 04:37:10 | Neg. Rate - Read:  - Raw: 0061N.9620 - Pre: 619.9899
  | 2022-08-03 04:32:19 | Neg. Rate - Read:  - Raw: 0061N.9520 - Pre: 619.9899
  | 2022-08-03 04:27:28 | Neg. Rate - Read:  - Raw: 0061N.9620 - Pre: 619.9899
  | 2022-08-03 04:08:04 | Neg. Rate - Read:  - Raw: 0061N.9620 - Pre: 619.9899
  | 2022-08-03 04:03:13 | Neg. Rate - Read:  - Raw: 0061N.9659 - Pre: 619.9899
  | 2022-08-03 03:38:58 | Neg. Rate - Read:  - Raw: 0061N.9659 - Pre: 619.9899
  | 2022-08-03 03:34:07 | Neg. Rate - Read:  - Raw: 0031N.9659 - Pre: 619.9899
  | 2022-08-03 03:29:16 | Neg. Rate - Read:  - Raw: 0061N.9659 - Pre: 619.9899
  | 2022-08-03 00:10:26 | Neg. Rate - Read:  - Raw: 0061N.9659 - Pre: 619.9899
  | 2022-08-03 00:05:35 | Neg. Rate - Read:  - Raw: 0061N.9701 - Pre: 619.9899
  | 2022-08-03 00:00:44 | Neg. Rate - Read:  - Raw: 0061N.9631 - Pre: 619.9899
```

**Comment by JensHoRi** [comment]
You did a reboot after new ROI configuration? Looks like he is still using old areas.

Furthermore the 9 will be read some later, because state is still between 8 and 9 on your reader

**Comment by ckoeber83** [comment]
Hi [JensHoRi](https://github.com/JensHoRi),

a reboot helps and loads the new alignment.
But actual the last RAW value was Raw: 00010.2329 which is totally wrong 
![image](https://user-images.githubusercontent.com/52466072/182565589-bbda5b7b-c01d-4786-9cfe-eb0500e5ffb1.png)

I will further investigate and report back.

**Comment by ckoeber83** [comment]
Also the next readings are wrong

```
  | 2022-08-03 10:51:28 | Neg. Rate - Read:  - Raw: 00010.2429 - Pre: 619.9899
  | 2022-08-03 10:46:37 | Neg. Rate - Read:  - Raw: 00010.2329 - Pre: 619.9899
  | 2022-08-03 10:41:46 | Neg. Rate - Read:  - Raw: 00010.2329 - Pre: 619.9899

```

**Comment by JensHoRi** [comment]
Just wait, for this you got the failure correction. If it permanently failes, try to readjust ROI

i have sometimes also 4 is read like 8, but every few cycles it’s read correct and so it’s fine. As long as only verified values are transmitted and that often enough

**Comment by ckoeber83** [comment]
Hi [JensHoRi](https://github.com/JensHoRi),

I have increase a bit the ROI frame and now the reading looks a bit better.
But he has actual not proper read the 4th and 5th digit:
![image](https://user-images.githubusercontent.com/52466072/182640643-014e4834-8312-4d20-979b-c633f541f3a4.png)

Will wait if they fix it due count cycle...

**Comment by JensHoRi** [comment]
Just wait for the 20 ;)

**Comment by jomjol** [comment]
Normally your digits should work - this kind of digits is part of the training data. Maybe the very thin numbers are making the problem. Then I would need training data (each number well aligned 2-3x).
The 0.1x, 0.01x and 0.001x will not work very well, as they are partly coverd or white on black (which is not part of the training).

**Comment by JensHoRi** [comment]
Hello jomjol, the black one has no needle, so I think the disc is rotating. In this case a small digital reading on top number should work, don’t it?

**Comment by jomjol** [comment]
yes, but this is also not part of the training and would need dedicated training data. It might not work with the digit numbers, as these are rolling from top to down and your "black needle" is running from left to right.

I fear, that this is one of the use cases, that need a special version and some special coding. This I cannot offer in this free version from my side. But if you extend the code, I more than happy to include later in my main branch.

**Comment by ckoeber83** [comment]
Hi,

now they reading 620 for some reason but my counter is passing 622
![image](https://user-images.githubusercontent.com/52466072/183090743-4646ac53-f457-4df6-8b17-119cb75df21d.png)

I rearrange the digital ROI and disable the Lock aspect ratio by placing the frames on the digits. Now I will see if that has any better effect:
![image](https://user-images.githubusercontent.com/52466072/183090634-ad9fa884-c88e-4cdc-bb28-54a0f4b8d61a.png)

Will report soon...

**Comment by JensHoRi** [comment]
> Hi,
> 
> now they reading 620 for some reason but my counter is passing 622

It had read the 622, see corrected value. Because 3 is half in the field it’s read as 9, the correction sees it and throws the result away. 

Don’t look on history of raw values, just look on values and they report right!!!

**Comment by jomjol** [comment]
> @jomjol i thought about Main (digits and one analog) and second counter with digital roi in the 8 ![2A654315-4BC7-45F6-8898-53434974DBA7](https://user-images.githubusercontent.com/47488279/183115794-1bcc322e-83de-4435-aecf-cd6250c610fc.jpeg) and then analog on the others, where you are right: some hidden parts makes it difficult to read.
> 
> But with digit on white 8 on black disc should be readable

Then you need to define each part of the reading as a separate number and put this together locally.

**Comment by JensHoRi** [comment]
Yes, two parts. As explained before ;) 

i try to assist a little bit in support. Hope that’s ok for you.

**Comment by haverland** [comment]
The issue comes when the First analog Counter is between 9.6 and 9.9. you could disable the analog rois as long as no fix is available or use the max rate less than 0.5

**Comment by ckoeber83** [comment]
Trying this one:

![image](https://user-images.githubusercontent.com/52466072/183448805-0e044094-5d38-427a-8257-e32368ea7eef.png)

**Comment by ckoeber83** [comment]
They have actual again issues with the 4th digit to identify:
![image](https://user-images.githubusercontent.com/52466072/183622343-c3223898-0105-4165-abc6-56d194a8fd96.png)

Will wait until the 3 is complete in line to check if the system identifies it....

**Comment by ckoeber83** [comment]
Unfortunately still does not work correctly. It is already back at 631, although the clock shows 630.

Does anyone have any more ideas?
I have the following settings:


![image](https://user-images.githubusercontent.com/52466072/183828330-bf4bcdcb-2293-483d-8604-6f4e108dc132.png)

```
[MakeImage]
;LogImageLocation = /log/source
WaitBeforeTakingPicture = 5
;LogfileRetentionInDays = 15
Brightness = -2
Contrast = 2
Saturation = 2
LEDIntensity = 3
ImageQuality = 12
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 87
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = false
/config/ref0.jpg 425 47
/config/ref1.jpg 104 156

[Digits]
Model = /config/dig1400s2q.tflite
;CNNGoodThreshold = 
;LogImageLocation = /log/digit
;LogfileRetentionInDays = 3
main.dig1 189 22 38 64
main.dig2 234 22 38 64
main.dig3 276 22 38 64
main.dig4 321 22 38 64
main.dig5 365 22 38 64

[Analog]
Model = /config/ana1000s2.tflite
;LogImageLocation = /log/analog
;LogfileRetentionInDays = 3
main.ana1 405 189 80 80
main.ana2 344 254 80 80
main.ana3 255 277 80 80
main.ana4 152 226 80 80

[PostProcessing]
main.DecimalShift = 0
PreValueUse = true
PreValueAgeStartup = 10080
AllowNegativeRates = false
main.MaxRateValue = 0.5
main.MaxRateType = RateChange
;main.ExtendedResolution = true
main.IgnoreLeadingNaN = true
;ErrorMessage = false
;CheckDigitIncreaseConsistency = false
```

**Comment by JensHoRi** [comment]
Change rate change to absolut change to prevent this.

**Comment by jomjol** [comment]
additionally I recommend to use a smaller value (e.g. 0.2 instead of 0.5). Ususally you should not have more than 200l change between two reading in a normal case.

**Comment by ckoeber83** [comment]
Hi,

I change now 
```
main.MaxRateValue = 0.2
main.MaxRateType = absolute
```

The watermeter is reading today a 0 in the last digital digit instead of an 3.
![image](https://user-images.githubusercontent.com/52466072/184356584-dfc4deb1-2218-4a02-91f2-53001dbd073c.png)

This happens yesterday at 06:20pm after successful reading 633.6799

```
  | 2022-08-11 18:25:50 | Neg. Rate - Read:  - Raw: 00630.6528 - Pre: 633.6799
  | 2022-08-11 18:20:59 | no error
  | 2022-08-11 18:16:08 | Neg. Rate - Read:  - Raw: 00633.5996 - Pre: 633.6622
```

Can I prevent this in the future?

**Comment by JensHoRi** [comment]
That will always happen, but no problem. Take the value if now error is reported and be happy. 

Don’t look on the error log: log at the successful results.

**Comment by jomjol** [comment]
Well, main problem ist, that your "3" in the last digit is obviously detected as an "0". This may happen from time to time. If this is a persitent problem, you need to provide training data to train your specific numbers.

**Comment by ckoeber83** [comment]
Hi jomlo,

how can I provide training data to train my specific numbers?

BR

**Comment by jomjol** [comment]
1. Setup your ROI according to the description in the wiki (https://github.com/jomjol/AI-on-the-edge-device/wiki/ROI-Configuration)
2. Turn on the logging for the images in the config.ini
3. Wait
4. Select 2-3 representative images from the collected images
5. put them in a zip-file and send to me (post in issue)

**Comment by ckoeber83** [comment]
Hi jomjol,

here my representative images from the collected images. From each number one example:

[digital_ROI.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9358361/digital_ROI.zip)
[analog_ROI.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9358362/analog_ROI.zip)

Let me know if you need more.
BR

**Comment by ckoeber83** [comment]
Can you tell me which trained file would be match best for my counters?
I found in [configs ](https://github.com/jomjol/AI-on-the-edge-device/tree/v11.0.1/sd-card/config) folder the following new trained files:

`ana-class100_0120_s1_q.tflite
ana-class100_i32s100dr-v1.0_q.tflite
ana-cont_1101_s2_q.tflite

dig-class100_0120_s2_q.tflite
dig-class100_s1d-md-v1.0_q.tflite
dig-class11_1411_s2_q.tflite
dig-cont_0560_s3_q.tflite`

**Comment by haverland** [comment]
For ana-class100 you can test it with:
https://github.com/haverland/collectmeteranalog 

pip install git+https://github.com/haverland/collectmeteranalog
python3 -m collectmeteranalog --labeling=./analog_ROI --model= <path_to_the_model>

For dig-class100 you can check it with 
https://github.com/haverland/collectmeterdigits 

pip install git+https://github.com/haverland/collectmeterdigits
python3 -m collectmeterdigits --labeling=./digital_ROI --model <path_to_the_model>


The prediction test for dig-cont currently are not implemented. Sorry.

And yes. dig-class/dig-cont for digit and  ana-class/ana-cont for pointers.

**Comment by haverland** [comment]
But I think the analog pointer will not have a good prediction in any way. The white ones are (except the last) not readable. And the black one has a complete other nature. It is not a pointer. Its more like a digit.

I would set ExtendedResolution=true and use only digits with dig-class100 or dig-cont. So you would have resolution of 100 liters. (not real, more like +/- 200l depending on the accuracy of the models)

**Comment by jomjol** [comment]
> Hi jomjol,
> 
> here my representative images from the collected images. From each number one example:
> 
> [digital_ROI.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9358361/digital_ROI.zip) [analog_ROI.zip](https://github.com/jomjol/AI-on-the-edge-device/files/9358362/analog_ROI.zip)
> 
> Let me know if you need more. BR

**This are way not enough images!**

For a training set I need images of all number.
* Digits: 0, 1, 2, 3, ... 9 --> each about 2-3 examles (if identical on each posistion, otherwise for each position 2-3 examples)
* Analog: full training set of 0.1, 0,2, 0.3, ... 9.8, 9.9 --> 100 images, also each 2 examples. If single images are missing, this is here not a big problem.

For the partial covered analog pointers I see no change, also for the black one, because it is running in a differnt mode (not pointer, but number rotation).

**Comment by caco3** [comment]
closing as incomplete and no response for a month. Feel free to re-open with new data/information.
